### ISSUE TITLE
I want to make certain enhancements in footer.

### ISSUE THREAD

**Issue by Manujdixit** [SimranS22/K-Quiz#6]

**Comment by Manujdixit** [comment]
AFTER
![Screenshot 2022-10-07 192219](https://user-images.githubusercontent.com/94791934/194570346-84ac53c7-6488-4025-88d9-2a6af922edd9.png)


BEFORE
![Screenshot 2022-10-07 192304](https://user-images.githubusercontent.com/94791934/194570442-963e58c9-9b30-4933-987a-a3ab12d81be0.png)

**Comment by SimranS22** [comment]
Are there any other changes you will be making because this seems a bit simple.

**Comment by Manujdixit** [comment]
@SimranS22 , working on it.
