### ISSUE TITLE
Move quiz data into it's own file

### ISSUE THREAD

**Issue by julicheng** [SimranS22/K-Quiz#7]
Right now all the quizzes has similar js in each file. I think it would be a good idea to refactor and move reused code into it's own file so that we can use it in multiple places.

Let me know what you think and I'll be happy to work on it 🙂

**Comment by SimranS22** [comment]
Sure.

Please provide screenshots or screen-recording of the altered webpage when making the pull request so that I can see what changes have been made. If you planning to add more sections. Send screenshots of those too.

Good luck!!
